# week05/k8s/order-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w05-aks
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: durgeshsamariya.azurecr.io/order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_HOST
          value: order-db-service-w05-aks
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w05-aks
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w05-aks
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w05-aks
              key: POSTGRES_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w05-aks
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w05-aks
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w05-aks
              key: RABBITMQ_PASS
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w05-aks
              key: PRODUCT_SERVICE_URL
        - name: CUSTOMER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w05-aks
              key: CUSTOMER_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-w05-aks
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: LoadBalancer
