name: Deploy to AKS (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Azure Authentication ---
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # --- Get AKS Context ---
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: orgil-aks
          resource-group: Deakin

      # --- Update image references to production images ---
      - name: Update image references
        run: |
          sed -i 's|image: .*frontend:.*|image: orgil.azurecr.io/frontend:latest|g' k8s/frontend.yaml
          sed -i 's|image: .*customer-service:.*|image: orgil.azurecr.io/customer-service:latest|g' k8s/customer-service.yaml
          sed -i 's|image: .*order-service:.*|image: orgil.azurecr.io/order-service:latest|g' k8s/order-service.yaml
          sed -i 's|image: .*product-service:.*|image: orgil.azurecr.io/product-service:latest|g' k8s/product-service.yaml

      # --- Deploy to Production Namespace ---
      - name: Deploy all Kubernetes manifests
        run: |
          kubectl apply -f k8s/ -n production --validate=false

      # --- Verify production deployment ---
      - name: Check production deployment status
        run: |
          kubectl get pods -n production
          kubectl get svc -n production
