name: Deploy to Staging

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create staging environment
        run: |
          kubectl create namespace staging || true
          kubectl apply -f k8s/staging/ -n staging

      - name: Deploy services to staging
        run: |
          kubectl set image deployment/frontend frontend=${{ env.REGISTRY_NAME }}/frontend:${{ env.IMAGE_TAG }} -n staging
          kubectl set image deployment/customer-service customer-service=${{ env.REGISTRY_NAME }}/customer_service:${{ env.IMAGE_TAG }} -n staging
          kubectl set image deployment/product-service product-service=${{ env.REGISTRY_NAME }}/product_service:${{ env.IMAGE_TAG }} -n staging
          kubectl set image deployment/order-service order-service=${{ env.REGISTRY_NAME }}/order_service:${{ env.IMAGE_TAG }} -n staging

      - name: Wait and run acceptance test (optional)
        run: |
          echo "Waiting for staging services to start..."
          sleep 60
          echo "Running acceptance tests..."
          # Replace with actual acceptance test commands or API checks

      - name: Destroy staging environment
        if: always()
        run: |
          kubectl delete namespace staging
